export enum TodosActionsFail{
    GET_TODOS_FAILED = 'GET_TODOS_FAILED',
    CREATE_TODO_FAILED = 'CREATE_TODO_FAILED',
    DELETE_TODO_FAILED = 'DELETE_TODO_FAILED',
    CHANGE_TODO_FAILED = 'COMPLITE_TODO_FAILED',
    COMPLITE_ALL_TODOS_FAILED = 'COMPLITE_ALL_TODOS_FAILED',
    DELETE_ALL_TODOS_FAILED = 'DELETE_ALL_TODOS_FAILED'
}
