export enum TodosActionsRequest{
    GET_TODOS_REQUESTED = 'GET_TODOS_REQUESTED',
    CREATE_TODO_REQUESTED = 'CREATE_TODO_REQUESTED',
    DELETE_TODO_REQUESTED = 'DELETE_TODO_REQUESTED',
    CHANGE_TODO_REQUESTED = 'COMPLITE_TODO_REQUESTED',
    COMPLITE_ALL_TODOS_REQUESTED = 'COMPLITE_ALL_TODOS_REQUESTED',
    DELETE_ALL_TODOS_REQUESTED = 'DELETE_ALL_TODOS_REQUESTED'
}
